
[env]
CLUTTER_PAINT = "disable-clipped-redraws:disable-culling"
CLUTTER_VBLANK = "True"
TERM = "alacritty"
__GLX_VENDOR_LIBRARY_NAME = "nvidia"
__NV_PRIME_RENDER_OFFLOAD = "1"

[font]
size = 12

[font.bold]
family = "JetBrains Mono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono NF"
style = "Italic"

[font.normal]
family = "JetBrains Mono NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control|Shift"

[window]
opacity = 0.75

[general]
import = ["/home/quythanh/.config/alacritty/mocha.toml"]
